### ISSUE TITLE
Time Values Displayed Incorrectly

### ISSUE THREAD

**Issue by mfairch** [michielfb/laravel-nova-time-field#2]
Thank you very much for creating this component as it's exactly what I need however I have observed some display issues.

This works perfectly for hours 01-12. It fails for 00, 13-24.

I also noticed when I edit a resource that the time field is blank and if I don't put a new value in, it will give a database error because the time that was selected is invalid.

**Example:**
12:00 AM (00:00)

Stored in Database Time Field as `00:00:00`
Displayed as `12:00 PM`

**Example:**
05:30 PM (17:30)

Stored in Database Time Field as `17:30:00`
Displayed as `05:30 AM`

**Example:**
07:00 AM (07:00)

Stored in Database Time Field as `07:00:00`
Displayed as `07:00 AM`

Code:
```
Time::make( 'Time of Day' )->format('HH:mm A')
```

Laravel 6.9.0
Nova 2.9.2

**Comment by michielfb** [comment]
@mfairch I've having difficulties replicating this bug. I tried all examples and they were displayed as expected. I'm using the same Laravel and Nova versions.

I did notice your example uses the format `HH:mm A`. I would have expected you use `hh:mm A` instead because according to the [momentjs docs](https://momentjs.com/docs/#/displaying/) that is the way to display a 12 hour time format. Can you try using `hh:mm A` as format?

**Comment by mfairch** [comment]
@michielfb thanks for looking at it. I tried the different format and it didn't work. Turns out I forgot I had an attribute override that formatted the date different so it was technically displaying correctly based on the new format I gave it.

```php
    public function getTimeOfDayAttribute( $value ) {
        return date( "g:iA", strtotime( $value ) );
    }
```
